### ISSUE TITLE
OCR0023: Create Google Books benchmark set.

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/Create_OCR_benchmark_data#7]
## Description:
We have line images and its transcripts from Google books already cropped out and uploaded to the s3. you need to download those data and create a benchmark set of those data for the google books.

## Reference:
Google Books data in the s3 are: https://s3.amazonaws.com/monlam.ai.ocr/Google_books/bo/
Scripts in repo: https://github.com/OpenPecha/Create_OCR_benchmark_data

## Completion Criteria:
upload all the train and eval set images to a directory in the s3 called `https://s3.amazonaws.com/monlam.ai.ocr/Data/OCR/Uchan/GoogleBooks/Train_Images/`
upload all the test set images to a directory in the s3 called `https://s3.amazonaws.com/monlam.ai.ocr/Data/OCR/Uchan/GoogleBooks/Test_Images/`
create three csvs
1. train.csv
2. eval.csv
3. test.csv
include all or any metadata it has with it.

## Implementation Plan

![Image](https://github.com/OpenPecha/Create_OCR_benchmark_data/assets/52460417/25570ef3-f8f0-4cb0-bb07-dfc83d8ce75d)

## Steps 

- [x] download zip files (line images and line texts)
- [x] unzip files
- [x] get stacks frequency from transcripts
- [ ] filter out stacks into rare and non rare stacks based on threshold
- [ ] script to get meta data about the stacks
### For rare stacks
- [ ] get set number of data from each work
- [ ] split into training, eval and test data set(Distribution=>43.5%, 43.5%, 13%)
- [ ] upload to s3 bucket
### For non rare stacks
- [ ] get set number of data from each work
- [ ] split into training, eval and test data set
- [ ] upload to s3 bucket

**Comment by tenzin3** [comment]
Number of works(zip files ) in Google_books/bo/text = 100
Number of works(zip files ) in Google_books/bo/numbers = 100

Important Note: 4 work ids in Google_books/bo/numbers are empty listed below
W1KG13117
W1AC428
W1KG12782
W1KG109100

After extraction:
Number of works(csv files ) in Google_books/bo/text = 100
Number of works(csv files ) in Google_books/bo/numbers = 96

**Comment by tenzin3** [comment]
**No of stacks:** 1367

**No of non punct stacks:** 594
**No of punct stacks:** 773

**Comment by tenzin3** [comment]
Blockage for now, since there is the filtering for rare stacks was'nt finalized. 

Outputs of work for now has been uploaded to a newly created bucket s3://ocr-google-books-benchmark/.
